networks:
  klwb_laravel:


services:

  mysql:
    image: mysql/mysql-server:8.0
    container_name: klwb_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    networks:
      - klwb_laravel

  phpmyadmin:
    container_name: klwb_admin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8086:80'
    env_file:
      - .env
    networks:
      - klwb_laravel